INSERT INTO question (content, number, test)
VALUES 
    ('Sabe próprio nome', 1, 1),
    ('Responde ao ''Não'' ou ''Pare''', 2, 1),
    ('Pode obedecer certas ordens', 3, 1),
    ('Consegue usar uma palavra por vez', 4, 1),
    ('Consegue usar 2 palavras juntas', 5, 1),
    ('Consegue usar 3 palavras juntas', 6, 1),
    ('Sabe 10 ou mais palavras', 7, 1),
    ('Consegue usar orações com 4 ou mais palavras', 8, 1),
    ('Explica o que quer', 9, 1),
    ('Faz perguntas com sentido', 10, 1),
    ('Sua linguagem costuma ser relevante/com sentido', 11, 1),
    ('Com frequência usa várias orações sucessivas', 12, 1),
    ('Mantém uma conversa razoavelmente boa', 13, 1),
    ('Tem capacidade normal de comunicação para a sua idade', 14, 1),
    ('Parece estar fechado em si mesmo - não é possível interagir com ele/ela', 15, 1),
    ('Não presta atenção nas pessoas', 16, 1),
    ('Mostra pouca ou nada de atenção quando falamos com ele', 17, 1),
    ('Não é cooperativo e é resistente', 18, 1),
    ('Não tem contato ocular', 19, 1),
    ('Prefere que o deixem sozinho', 20, 1),
    ('Não demonstra afeto', 21, 1),
    ('Não cumprimenta os pais', 22, 1),
    ('Evita contato com outras pessoas', 23, 1),
    ('Não imita', 24, 1),
    ('Não gosta que lhe abracem ou acariciem', 25, 1),
    ('Não compartilha/mostra coisas aos outros', 26, 1),
    ('Não se despede fazendo tchau', 27, 1),
    ('Desagradável/desobediente', 28, 1),
    ('Birras', 29, 1),
    ('Não tem amigos/companheiros', 30, 1),
    ('Sorri muito pouco', 31, 1),
    ('Insensível aos sentimentos dos outros', 32, 1),
    ('Não tem interesse em agradar os outros', 33, 1),
    ('Fica indiferente quando os pais vão embora, se distanciam', 34, 1),
    ('Responde ao próprio nome', 35, 1),
    ('Reconhece quando é elogiado', 36, 1),
    ('Olha para as pessoas e animais', 37, 1),
    ('Assiste desenhos na TV', 38, 1),
    ('Desenha, colore, faz objetos de arte', 39, 1),
    ('Brinca com os brinquedos de forma correta', 40, 1),
    ('Tem uma expressão facial apropriada', 41, 1),
    ('Entende as histórias da TV', 42, 1),
    ('Entende as suas explicações', 43, 1),
    ('Está consciente do ambiente que lhe rodeia', 44, 1),
    ('Tem consciência de perigo', 45, 1),
    ('Mostra imaginação', 46, 1),
    ('Inicia atividades', 47, 1),
    ('Se veste sozinho', 48, 1),
    ('Curioso, interessado', 49, 1),
    ('Se aventura, explora', 50, 1),
    ('Sintonizado, não parece estar ''nas nuvens''', 51, 1),
    ('Olha para onde os outros olham', 52, 1),
    ('Enuresis (urina na cama)', 53, 1),
    ('Urina nas calças ou fralda', 54, 1),
    ('Defeca nas calças ou fralda', 55, 1),
    ('Diarreia', 56, 1),
    ('Prisão de ventre', 57, 1),
    ('Problemas para dormir', 58, 1),
    ('Come muito/muito pouco', 59, 1),
    ('Dieta extremamente limitada, não aceita qualquer comida', 60, 1),
    ('Hiperativo', 61, 1),
    ('Letárgico', 62, 1),
    ('Machuca a si mesmo', 63, 1),
    ('Machuca os outros', 64, 1),
    ('Destrutivo', 65, 1),
    ('Sensível a barulho', 66, 1),
    ('Ansioso/medroso', 67, 1),
    ('Triste/chora', 68, 1),
    ('Convulsões', 69, 1),
    ('Fala/linguagem obsessiva', 70, 1),
    ('Rotinas rígidas', 71, 1),
    ('Grita', 72, 1),
    ('Exige que as coisas sejam sempre feitas da mesma forma', 73, 1),
    ('Com frequência fica agitado', 74, 1),
    ('Não é sensível a dor', 75, 1),
    ('Obcecado com certos objetos/temas', 76, 1),
    ('Faz gestos, movimentos repetitivos', 77, 1);
